name: "ADO Migration Guide: Work Items"
description: "Form for Work Item Migration"
title: "[Work Item Migration]: "
labels: ["Work Item"]
body:
  - type: markdown
    value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
